### ISSUE TITLE
Where to get the dll?

### ISSUE THREAD

**Issue by Kijaru** [dtzxporter/Siren#2]
Hello,

Since your code is based on dlls, i was wondering if you knew a place where to get the 7 x86 library? Warframe stopped supporting x86, and therefore removed all the 32bit libraries from their client before i could get my hands on it...

Thank you,

**Comment by dtzxporter** [comment]
All of the files are from various games, sometimes the older / newer ones will work fine if you can find one... Though, it is 2019, there is no reason to not compile for 64bit at this point...
